### PR TITLE
Fix Bug that Creates an Empty Primary Contact Person

### PR DESCRIPTION
**Pull request by katelynsills**
## Description
Fixes the bug that creates an empty primary contact person when the front end doesn't send in a primaryContactPerson object.

The problem was that `updateCreatePrimaryContactPerson` was supposed to return early if primaryContactPerson was null or undefined, but it needed a return to do so. 

I also fixed a number of other similar cases so that we don't have the same problem in the future. Here's to learning more about promises the hard way! 😄 

## Test Plan
`yarn test`
or, test in the front end

### CODE REVIEW

**Comment by karenmrose** [comment]
Sweet! I tested the case where there is no primary contact and that works great.

It looks like when you already have a primaryContactPerson and then change something (for example, the phone number), it creates another `Person` record rather than updating the original one by the `primaryContactPerson._id`.

**Comment by katelynsills** [comment]
Dang, thanks for catching that. I'll take a look.

**Comment by katelynsills** [comment]
I took a look, and I think it's a front-end issue. The front-end isn't sending an _id for the old primaryContactPerson:  
``` "primaryContactPerson":{"firstName":"Kate2","lastName":"Sills2","phone":"+19167163024","email":"katelynsills@gmail.com2"},```

**Comment by karenmrose** [comment]
Fixed!

**Comment by katelynsills** [comment]
awesome!!

**Comment by karenmrose** [comment]
> Here's to learning more about promises the hard way! 😄

Haha

**Comment by karenmrose** [comment]
Ok looks good, let's merge it!!

**Pull request merged**
