### PR TITLE
Switch to sending Facebook Access Tokens to the API for Authentication

### PR DESCRIPTION
**Pull request by katelynsills**
## Description
This pull request changes the passport strategy to `facebookTokenStrategy` instead of `facebookStrategy`.  With `facebookTokenStrategy` the API accepts a facebook access token from the client. This lets us decouple the frontend from the backend so that the API is truly independent. Before this, the frontend would have to share the same state as the backend, or the API would have to have a user authenticate by going through the Facebook permission screen. Now, the user can authenticate on the frontend only, and the frontend can send the access token to the authentication endpoint (see test plan for details). 

-- Edit: In order to test the authentication, I added in the `morgan` package which logs each route hit. 

## Test Plan
To test, go to `https://developers.facebook.com/tools/explorer/` to get an access token. (Use the application dropdown to select Help Assist Her Verification). With the server running, try to access one of the routes, such as:

```http://127.0.0.1:4000/api/pregnancy-centers/verify``` 

You'll get this error: `{"statusCode":401,"error":"Unauthorized","message":"User is not logged in."}`

Then hit this route, inserting the token you got from Facebook:

```http://127.0.0.1:4000/auth/facebook/token?access_token=[token]```

You will get a 200 response with this message: `"Authentication successful."`

Then visit the first route (`http://127.0.0.1:4000/api/pregnancy-centers/verify`) again, and you'll get one pregnancy center to verify as expected.

Then hit `http://127.0.0.1:4000/logout` and you will be unauthorized again.

### CODE REVIEW

**Comment by karenmrose** [comment]
Let me know if/when you need to get this one merged. I want to take a look with the changes I'll need to make on the FE, but I'm still in redux land at the moment. If it's blocking you though, I can switch and get this reviewed.

**Comment by katelynsills** [comment]
Thanks, Karen! I had stacked the Travis CI pull request on top of this one for some reason, and I think it'd be helpful to get the Travis CI one merged in, so I probably will be blocked without it, but I probably won't have time to work on this for the next few days anyway. 

If it helps, I think the main changes on the frontend will be:

1. Adding a button that contacts Facebook and asks the user for permission, then returns an access token for the app. I think this will do it: https://www.npmjs.com/package/react-facebook-login 
2. In the responseFacebook callback of the react component, I think we can make the authentication call to `/auth/facebook/token?access_token=[token]` instead of calling `auth/facebook` elsewhere.

After that, I think the other API calls in the same session should work.

**Comment by karenmrose** [comment]
I'm going to merge this in so that I can make the FE updates!

**Comment by katelynsills** [comment]
Ok cool!

**Pull request merged**
