### PR TITLE
Added toggle switch per volunteer take home problem

### PR DESCRIPTION
**Pull request by AndrewPHunter**
## Description
Added the toggle switch based on the specification for the take home problem and invision document.

## Test Plan

* Add the component where desired on test page
* The props required to pass in to the component are `toggle` and `onClick` which represent the toggle state and click event
* The `toggle` state is managed by the parent component per the spec and example usage as follows:

```js
//..other dependencies
import Toggle from '../components/Toggle'

export default class someParentComponent extends Component{
    constructor(props){
        super(props);
        this.state = {
            toggle: false
            //other state
        };
    }

    onToggle = (event)=>{
        event.preventDefault();
        this.setState((prevState)=>({
            ...prevState,
            toggle: !prevState.toggle
        }));
    };
    
    render(){
        return(
            <Toggle toggle={this.state.toggle}
                    onClick={this.onToggle}
             />
        );
    }
}
```

### CODE REVIEW

**Comment by AndrewPHunter** [comment]
Hi @karenmrose !  I actually have a create-react-app laying around for when I am manual testing components out of band. I generally try to stay away from dropping things into existing code bases just to manually test them out.  I will add the manual testing steps to the test plan.

**Comment by AndrewPHunter** [comment]
@karenmrose example usage for manual testing plan has been added. Let me know if you want this in some other format or we could use some automated snapshot and UI testing. I just didn't want to add dependencies without direction from you.

**Comment by karenmrose** [comment]
@AndrewPHunter The fields that we will put the toggle on are:
- Name
- Address Line 1
- Phone Number
- Email
- Website
- Services
- Hours

If you want to stack the PRs and actually add the toggle to the form in a separate PR to keep it clean, that is fine, we'll just merge them at the same time so that we can test and make sure it's working before merging. Also, don't worry about removing the current "verified" checkboxes yet, we can do that separately so that it doesn't add too much to the PR(s). Let me know if you have any questions!

**Comment by karenmrose** [comment]
Hey @AndrewPHunter, just wanted to check in and see how this is going?

**Pull request closed without merging**
